services:
  mongo:
    image: mongo:4.2.5
    volumes:
      - mongo_data:/data/db
  app:
    build: .
    environment:
      WAIT_HOSTS: mongo:27017
      DOCKER_DB: "true"
    ports:
      - '8080:8000'
    volumes:
      # - ./logs:/app/logs
      - .:/mnt
      - ./public/pfps:/app/public/pfps
volumes:
  mongo_data: